version: 2.1

jobs:
  build-and-push-image:
    docker:
      - image: google/cloud-sdk:latest 
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Specify Docker version
      - run:
          name: Authenticate with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project theta-turbine-417512
            gcloud auth configure-docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t gcr.io/theta-turbine-417512/nft-marketplace:$CIRCLE_SHA1 .
            docker push gcr.io/theta-turbine-417512/nft-marketplace:$CIRCLE_SHA1

  deploy-to-gke:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate with GCP for kubectl
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project theta-turbine-417512
            gcloud --quiet config set compute/zone your-compute-zone
            gcloud container clusters get-credentials your-cluster-name
      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f ./k8s/deployment.yaml
            kubectl apply -f ./k8s/service.yaml
            # Add other k8s manifests as needed
            # e.g., kubectl apply -f ./k8s/hpa.yaml

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image
      - deploy-to-gke:
          requires:
            - build-and-push-image
