version: 2.1

jobs:
  build-and-push:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image and push to GCR
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project theta-turbine-417512
            gcloud --quiet config set compute/zone your-zone
            gcloud auth configure-docker
            docker build -t gcr.io/theta-turbine-417512/nft-marketplace:$CIRCLE_SHA1 .
            docker push gcr.io/theta-turbine-417512/nft-marketplace:$CIRCLE_SHA1

  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          name: Deploy to GKE
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project theta-turbine-417512
            gcloud --quiet config set compute/zone your-zone
            gcloud container clusters get-credentials nft-marketplace-cluster
            kubectl set image deployment/nft-marketplace-deployment nft-marketplace-container=gcr.io/theta-turbine-417512/nft-marketplace:$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push
