version: 2.1

jobs:
  build-and-push-image:
    docker:
      - image: google/cloud-sdk:latest # This image has `gcloud` installed
    steps:
      - checkout
      - setup_remote_docker: # Required for Docker commands
          version: 20.10.7 # Specify Docker version
      - run:
          name: Authenticate with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project theta-turbine-417512
            gcloud auth configure-docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t gcr.io/theta-turbine-417512/nft-marketplace:$CIRCLE_SHA1 .
            docker push gcr.io/theta-turbine-417512/nft-marketplace:$CIRCLE_SHA1

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image
