apiVersion: v1
kind: Service
metadata:
  name: nft-marketplace-service
  labels:
    app: nft-marketplace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nft-marketplace
